version: "3.8"

services:
  server1:
    build: ./server
    environment:
      - PORT=5001
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - app-net
    restart: "always"

  server2:
    build: ./server
    environment:
      - PORT=5002
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - app-net
    restart: "always"

  server3:
    build: ./server
    environment:
      - PORT=5003
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - app-net
    restart: "always"

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - app-net

  nginx:
    restart: always
    image: "nginx:latest"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "81:81"
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - app-net

volumes:
  data:
  logs:

networks:
  app-net:
    driver: bridge
